services:
  api:
    build: .
    container_name: api
    command: bash -c "cd src/rest && python manage.py runserver 0.0.0.0:8000"
    # command : bash -c "cd src/rest && ls" 
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      # - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      # - ${ADBREW_CODEBASE_PATH}:/src
      - ./:/src
    environment:
      - PYTHONUNBUFFERED=1

  app:
    build: .
    container_name: app
    command: bash -c "cd src/app && yarn start"
    # command : bash -c "ls" 
    ports:
      - "3000:3000"
    volumes:
      # - ${ADBREW_CODEBASE_PATH}:/src
        - ./:/src
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db:/data/db
    command: --bind_ip 0.0.0.0

volumes:
  db: